;; Copyright (c) Stuart Sierra, 2012. All rights reserved.  The use
;; and distribution terms for this software are covered by the Eclipse
;; Public License 1.0 (http://opensource.org/licenses/eclipse-1.0.php)
;; which can be found in the file epl-v10.html at the root of this
;; distribution.  By using this software in any fashion, you are
;; agreeing to be bound by the terms of this license.  You must not
;; remove this notice, or any other, from this software.

(ns ^{:author "Stuart Sierra"
      :doc "JavaScript Object Notation (JSON) parser/generator.
  See http://www.json.org/"
      :lang :core.typed
      ;:core.typed {:features #{:runtime-infer}}
      }
  clojure.data.json
  (:refer-clojure :exclude (read))
  (:require [clojure.pprint :as pprint]
            [clojure.core.typed :as t]
            [clojure.spec :as s])
  (:import (java.io PrintWriter PushbackReader StringWriter
                    Writer StringReader EOFException)))

;; Start: Generated by clojure.core.typed - DO NOT EDIT
(declare a-b)
(t/defalias a-b (t/Map t/Any t/Any))
(t/ann
  -read
  [PushbackReader
   Boolean
   t/Any
   :->
   t/Any])
(t/ann
  codepoint-clause
  [(t/I t/Sequential (t/Coll t/Any))
   :->
   '[(t/U t/Int (t/Coll t/Int)) t/Any]])
(t/ann default-value-fn [t/Any t/Any :-> t/Any])
(t/ann
  default-write-key-fn
  [t/Any :-> t/Str])
(t/ann
  pprint
  [t/Any 
   & :optional {:escape-unicode Boolean
                :escape-js-separators Boolean
                :escape-slash Boolean
                :key-fn [t/Any :-> t/Any]}
   :-> t/Any])
(t/ann ^:no-check pprint-array [(t/U nil (t/Seqable t/Any)) :-> nil]) ;; uses pprint internals
(t/ann pprint-dispatch [t/Any :-> nil])
(t/ann pprint-generic [t/Any :-> nil])
(t/ann ^:no-check pprint-object [java.util.Map :-> nil]) ;; uses pprint internals
(t/ann
  read
  [java.io.Reader
   & :optional {:eof-error? Boolean
                :eof-value  t/Any
                :bigdec Boolean
                :key-fn [t/Any :-> t/Any]
                :value-fn [t/Any t/Any :-> t/Any]}
   :->
   t/Any])
(t/ann ^:no-check read-array [PushbackReader :-> (t/Vec t/Any)]) ;; need transient support in core.typed
(t/ann read-decimal [t/Str :-> (t/U Double BigDecimal)])
(t/ann read-escaped-char [PushbackReader :-> Character])
(t/ann read-hex-char [PushbackReader :-> Character])
(t/ann read-integer [t/Str :-> (t/U t/Int clojure.lang.BigInt)])
(t/ann
  read-number
  [PushbackReader :-> (t/U t/Num clojure.lang.BigInt BigDecimal)])
(t/ann ^:no-check read-object [PushbackReader :-> (t/Map t/Str t/Any)]) ;; need transient support in core.typed
(t/ann read-quoted-string [PushbackReader :-> t/Str])
(t/ann
  ^:no-check
  read-str ;; core.typed can't check apply'ed kw args
  [t/Str
   & :optional {:eof-error? Boolean
                :eof-value  t/Any
                :bigdec Boolean
                :key-fn [t/Any :-> t/Any]
                :value-fn [t/Any t/Any :-> t/Any]}
   :->
   t/Any])
(t/ann value-fn-sentinel Object)
(t/ann
  write
  [t/Any java.io.Writer 
   & :optional {:escape-unicode Boolean
                :escape-js-separators Boolean
                :escape-slash Boolean
                :key-fn [t/Any :-> t/Any]
                :value-fn [t/Any t/Any :-> t/Any]}
   :-> t/Any])
(t/ann
  write-array
  [(t/U (t/Set t/Int) (t/Coll (t/U nil t/Int))) PrintWriter :-> nil])
(t/ann
  write-bignum
  [(t/U clojure.lang.BigInt BigDecimal) PrintWriter :-> nil])
(t/ann write-double [Double PrintWriter :-> nil])
(t/ann write-float [Float PrintWriter :-> t/Any])
(t/ann write-generic [Object PrintWriter :-> t/Any])
(t/ann write-named [t/Sym PrintWriter :-> nil])
(t/ann write-null [nil PrintWriter :-> nil])
(t/ann
  write-object
  [(t/Map t/Any t/Any) PrintWriter :-> nil])
(t/ann write-plain [(t/U t/Int Boolean) PrintWriter :-> nil])
(t/ann write-ratio [clojure.lang.Ratio PrintWriter :-> t/Any])
(t/ann
  write-str
  [t/Any
   & :optional {:escape-unicode Boolean
                :escape-js-separators Boolean
                :escape-slash Boolean
                :key-fn [t/Any :-> t/Any]
                :value-fn [t/Any t/Any :-> t/Any]}
   :-> t/Str])
(t/ann write-string [t/Str PrintWriter :-> nil])
(t/ann clojure.pprint/pprint [t/Any :-> nil])
(t/ann *bigdec* Boolean)
(t/ann *key-fn* [t/Any -> t/Any])
(t/ann *value-fn* [t/Any t/Any -> t/Any])
(t/ann *escape-unicode* Boolean)
(t/ann *escape-js-separators* Boolean)
(t/ann *escape-slash* Boolean)
(t/ann-protocol JSONWriter -write [t/Any t/Any :-> t/Any])

;; End: Generated by clojure.core.typed - DO NOT EDIT
;;; JSON READER

(defonce value-fn-sentinel (Object.))

(def ^{:dynamic true :private true} *bigdec*)
(def ^{:dynamic true :private true} *key-fn*)
(def ^{:dynamic true :private true} *value-fn*)

(defn- default-write-key-fn
  [x]
  (cond (instance? clojure.lang.Named x)
        (name x)
        (nil? x)
        (throw (Exception. "JSON object properties may not be nil"))
        :else (str x)))

(defn- default-value-fn [k v] v)

(declare -read)

(defmacro ^:private codepoint [c]
  (int c))

(defn- codepoint-clause [[test result]]
  (cond (list? test)
        (let [_ (assert (seqable? test))]
          [(map (t/fn [i]
                  {:pre [(or (number? i)
                             (char? i))]}
                  (int i))
                test) result])
        (= test :whitespace)
        ['(9 10 13 32) result]
        (= test :simple-ascii)
        [(remove #{(codepoint \") (codepoint \\) (codepoint \/)}
                 (range 32 127))
         result]
        (= test :js-separators)
        ['(16r2028 16r2029) result]
        :else
        [(int (t/cast (t/U Character t/Int) test)) result]))

(defmacro ^:private codepoint-case [e & clauses]
  `(case ~e
     ~@(mapcat codepoint-clause (partition 2 clauses))
     ~@(when (odd? (count clauses))
         [(last clauses)])))

(defn- read-array [^PushbackReader stream]
  ;; Expects to be called with the head of the stream AFTER the
  ;; opening bracket.
  (loop [^{::t/ann (clojure.lang.ITransientVector t/Any)} result (transient [])]
    (let [c (.read stream)]
      (when (neg? c)
        (throw (EOFException. "JSON error (end-of-file inside array)")))
      (codepoint-case c
        :whitespace (recur result)
        \, (recur result)
        \] (persistent! result)
        (do (.unread stream c)
            (let [element (-read stream true nil)]
              (recur (conj! result element))))))))

(defn- read-object [^PushbackReader stream]
  ;; Expects to be called with the head of the stream AFTER the
  ;; opening bracket.
  (loop [^{::t/ann (t/U nil t/Str)} key nil, ^{::t/ann (t/U clojure.lang.PersistentHashMap$TransientHashMap clojure.lang.PersistentArrayMap$TransientArrayMap)} result (transient {})]
    (let [c (.read stream)]
      (when (neg? c)
        (throw (EOFException. "JSON error (end-of-file inside object)")))
      (codepoint-case c
        :whitespace (recur key result)

        \, (recur nil result)

        \: (recur key result)

        \} (if (nil? key)
             (persistent! result)
             (throw (Exception. "JSON error (key missing value in object)")))

        (do (.unread stream c)
            (let [element (-read stream true nil)]
              (if (nil? key)
                (if (string? element)
                  (recur element result)
                  (throw (Exception. "JSON error (non-string key in object)")))
                (recur nil
                       (let [out-key (*key-fn* key)
                             out-value (*value-fn* out-key element)]
                         (if (or (= *value-fn* out-value)
                                 (identical? value-fn-sentinel out-value))
                           result
                           (assoc! result out-key out-value)))))))))))

(defn- read-hex-char [^PushbackReader stream]
  ;; Expects to be called with the head of the stream AFTER the
  ;; initial "\u".  Reads the next four characters from the stream.
  (let [a (.read stream)
        b (.read stream)
        c (.read stream)
        d (.read stream)]
    (when (or (neg? a) (neg? b) (neg? c) (neg? d))
      (throw (EOFException.
              "JSON error (end-of-file inside Unicode character escape)")))
    (let [s (str (char a) (char b) (char c) (char d))]
      (char (Integer/parseInt s 16)))))

(defn- read-escaped-char [^PushbackReader stream]
  ;; Expects to be called with the head of the stream AFTER the
  ;; initial backslash.
  (let [c (.read stream)]
    (when (neg? c)
      (throw (EOFException. "JSON error (end-of-file inside escaped char)")))
    (codepoint-case c
      (\" \\ \/) (char c)
      \b \backspace
      \f \formfeed
      \n \newline
      \r \return
      \t \tab
      \u (read-hex-char stream))))

(defn- read-quoted-string [^PushbackReader stream]
  ;; Expects to be called with the head of the stream AFTER the
  ;; opening quotation mark.
  (let [buffer (StringBuilder.)]
    (loop []
      (let [c (.read stream)]
        (when (neg? c)
          (throw (EOFException. "JSON error (end-of-file inside string)")))
        (codepoint-case c
          \" (str buffer)
          \\ (do (.append buffer (read-escaped-char stream))
                 (recur))
          (do (.append buffer (char c))
              (recur)))))))

(defn- read-integer [^String string]
  (if (< (count string) 18)  ; definitely fits in a Long
    (t/cast Long (Long/valueOf string))
    (or (try (t/cast Long (Long/valueOf string))
             (catch NumberFormatException e nil))
        (bigint string))))

(defn- read-decimal [^String string]
  (if *bigdec*
    (bigdec string)
    (t/cast Double (Double/valueOf string))))

(defn- read-number [^PushbackReader stream]
  (let [buffer (StringBuilder.)
        decimal? (loop [^{::t/ann Boolean} decimal? false]
                   (let [c (.read stream)]
                     (codepoint-case c
                       (\- \+ \0 \1 \2 \3 \4 \5 \6 \7 \8 \9)
                       (do (.append buffer (char c))
                           (recur decimal?))
                       (\e \E \.)
                       (do (.append buffer (char c))
                           (recur true))
                       (do (.unread stream c)
                           decimal?))))]
    (if decimal?
      (read-decimal (str buffer))
      (read-integer (str buffer)))))

(defn- -read
  [^PushbackReader stream eof-error? eof-value]
  (loop []
    (let [c (.read stream)]
      (if (neg? c) ;; Handle end-of-stream
        (if eof-error?
          (throw (EOFException. "JSON error (end-of-file)"))
          eof-value)
        (codepoint-case
          c
          :whitespace (recur)

          ;; Read numbers
          (\- \0 \1 \2 \3 \4 \5 \6 \7 \8 \9)
          (do (.unread stream c)
              (read-number stream))

          ;; Read strings
          \" (read-quoted-string stream)

          ;; Read null as nil
          \n (if (and (= (codepoint \u) (.read stream))
                      (= (codepoint \l) (.read stream))
                      (= (codepoint \l) (.read stream)))
               nil
               (throw (Exception. "JSON error (expected null)")))

          ;; Read true
          \t (if (and (= (codepoint \r) (.read stream))
                      (= (codepoint \u) (.read stream))
                      (= (codepoint \e) (.read stream)))
               true
               (throw (Exception. "JSON error (expected true)")))

          ;; Read false
          \f (if (and (= (codepoint \a) (.read stream))
                      (= (codepoint \l) (.read stream))
                      (= (codepoint \s) (.read stream))
                      (= (codepoint \e) (.read stream)))
               false
               (throw (Exception. "JSON error (expected false)")))

          ;; Read JSON objects
          \{ (read-object stream)

          ;; Read JSON arrays
          \[ (read-array stream)

          (throw (Exception.
                  (str "JSON error (unexpected character): " (char c)))))))))

(defn read
  "Reads a single item of JSON data from a java.io.Reader. Options are
  key-value pairs, valid options are:

     :eof-error? boolean

        If true (default) will throw exception if the stream is empty.

     :eof-value Object

        Object to return if the stream is empty and eof-error? is
        false. Default is nil.

     :bigdec boolean

        If true use BigDecimal for decimal numbers instead of Double.
        Default is false.

     :key-fn function

        Single-argument function called on JSON property names; return
        value will replace the property names in the output. Default
        is clojure.core/identity, use clojure.core/keyword to get
        keyword properties.

     :value-fn function

        Function to transform values in maps (\"objects\" in JSON) in
        the output. For each JSON property, value-fn is called with
        two arguments: the property name (transformed by key-fn) and
        the value. The return value of value-fn will replace the value
        in the output. If value-fn returns itself or `value-fn-sentinel`, 
        the property will be omitted from the output. The default value-fn 
        returns the value unchanged. This option does not apply to non-map
        collections."
  [reader & options]
  (let [{:keys [eof-error? eof-value bigdec key-fn value-fn]
         :or {bigdec false
              eof-error? true
              key-fn identity
              value-fn default-value-fn}} options]
    (binding [*bigdec* bigdec
              *key-fn* key-fn
              *value-fn* value-fn]
      (-read (PushbackReader. reader) eof-error? eof-value))))

(defn read-str
  "Reads one JSON value from input String. Options are the same as for
  read."
  [string & options]
  (apply read (StringReader. string) options))

;;; JSON WRITER

(def ^{:dynamic true :private true} *escape-unicode*)
(def ^{:dynamic true :private true} *escape-js-separators*)
(def ^{:dynamic true :private true} *escape-slash*)

(t/tc-ignore
(defprotocol JSONWriter
  (-write [object out]
    "Print object to PrintWriter out as JSON"))
)

(defn- write-string [^CharSequence s ^PrintWriter out]
  (let [sb (StringBuilder. (count s))]
    (.append sb \")
    (dotimes [^{::t/ann t/Int} i (count s)]
      (let [cp (int (t/cast Character (.charAt s (int i))))]
        (codepoint-case cp
          ;; Printable JSON escapes
          \" (.append sb "\\\"")
          \\ (.append sb "\\\\")
          \/ (.append sb (if *escape-slash* "\\/" "/"))
          ;; Simple ASCII characters
          :simple-ascii (.append sb (.charAt s (int i)))
          ;; JSON escapes
          \backspace (.append sb "\\b")
          \formfeed  (.append sb "\\f")
          \newline   (.append sb "\\n")
          \return    (.append sb "\\r")
          \tab       (.append sb "\\t")
          ;; Unicode characters that Javascript forbids raw in strings
          :js-separators (if *escape-js-separators*
                           (.append sb (format "\\u%04x" cp))
                           (.appendCodePoint sb cp))
          ;; Any other character is Unicode
          (if *escape-unicode*
            (.append sb (format "\\u%04x" cp)) ; Hexadecimal-escaped
            (.appendCodePoint sb cp)))))
    (.append sb \")
    (.print out (str sb))))

(defn- write-object [m ^PrintWriter out] 
  (.print out \{)
  (loop [^{::t/ann (t/NilableNonEmptySeq '[t/Any t/Any])} x (seq m), ^{::t/ann Boolean} have-printed-kv false]
    (when (seq x)
      (let [[k v] (first x)
            out-key (*key-fn* k)
            out-value (*value-fn* k v)
            nxt (next x)]
        (when-not (string? out-key)
          (throw (Exception. "JSON object keys must be strings")))
        (if-not (or (= *value-fn* out-value)
                    (identical? value-fn-sentinel out-value))
          (do
            (when have-printed-kv
              (.print out \,))
            (write-string out-key out)
            (.print out \:)
            (-write out-value out)
            (when (seq nxt)
              (recur nxt true)))
          (when (seq nxt)
            (recur nxt have-printed-kv))))))
  (.print out \}))

(defn- write-array [s ^PrintWriter out]
  (.print out \[)
  (loop [^{::t/ann (t/U (t/Set t/Int) (t/Coll (t/U nil t/Int)))} x s]
    (when (seq x)
      (let [fst (first x)
            nxt (next x)]
        (-write fst out)
        (when (seq nxt)
          (.print out \,)
          (recur nxt)))))
  (.print out \]))

(defn- write-bignum [x ^PrintWriter out]
  (.print out (str x)))

(defn- write-float [^Float x ^PrintWriter out]
  (cond (.isInfinite x)
        (throw (Exception. "JSON error: cannot write infinite Float"))
        (.isNaN x)
        (throw (Exception. "JSON error: cannot write Float NaN"))
        :else
        (.print out x)))

(defn- write-double [^Double x ^PrintWriter out]
  (cond (.isInfinite x)
        (throw (Exception. "JSON error: cannot write infinite Double"))
        (.isNaN x)
        (throw (Exception. "JSON error: cannot write Double NaN"))
        :else
        (.print out x)))

(defn- write-plain [x ^PrintWriter out]
  (.print out x))

(defn- write-null [x ^PrintWriter out]
  (.print out "null"))

(defn- write-named [x out]
  (write-string (name x) out))

(defn- write-generic [x out]
  (if (some-> (t/ann-form (class x) (t/U nil Class)) .isArray)
    (do
      (assert (seqable? x))
      (-write (seq x) out))
    (throw (Exception. (str "Don't know how to write JSON of " (class x))))))

(defn- write-ratio [x out]
  (-write (double x) out))

(t/tc-ignore
;; nil, true, false
(extend nil                    JSONWriter {:-write write-null})
(extend java.lang.Boolean      JSONWriter {:-write write-plain})

;; Numbers
(extend java.lang.Byte         JSONWriter {:-write write-plain})
(extend java.lang.Short        JSONWriter {:-write write-plain})
(extend java.lang.Integer      JSONWriter {:-write write-plain})
(extend java.lang.Long         JSONWriter {:-write write-plain})
(extend java.lang.Float        JSONWriter {:-write write-float})
(extend java.lang.Double       JSONWriter {:-write write-double})
(extend clojure.lang.Ratio     JSONWriter {:-write write-ratio})
(extend java.math.BigInteger   JSONWriter {:-write write-bignum})
(extend java.math.BigDecimal   JSONWriter {:-write write-bignum})
(extend java.util.concurrent.atomic.AtomicInteger JSONWriter {:-write write-plain})
(extend java.util.concurrent.atomic.AtomicLong    JSONWriter {:-write write-plain})
;; Attempt to support Clojure 1.2.x:
(when-let [class (try (.. Thread currentThread getContextClassLoader
                          (loadClass "clojure.lang.BigInt"))
                      (catch ClassNotFoundException _ false))]
  (extend class JSONWriter {:-write write-bignum}))


;; Symbols, Keywords, and Strings
(extend clojure.lang.Named     JSONWriter {:-write write-named})
(extend java.lang.CharSequence JSONWriter {:-write write-string})

;; Collections
(extend java.util.Map          JSONWriter {:-write write-object})
(extend java.util.Collection   JSONWriter {:-write write-array})

;; Maybe a Java array, otherwise fail
(extend java.lang.Object       JSONWriter {:-write write-generic})
)

(defn write
  "Write JSON-formatted output to a java.io.Writer. Options are
   key-value pairs, valid options are:

    :escape-unicode boolean

       If true (default) non-ASCII characters are escaped as \\uXXXX

    :escape-js-separators boolean

       If true (default) the Unicode characters U+2028 and U+2029 will
       be escaped as \\u2028 and \\u2029 even if :escape-unicode is
       false. (These two characters are valid in pure JSON but are not
       valid in JavaScript strings.)

    :escape-slash boolean

       If true (default) the slash / is escaped as \\/

    :key-fn function

        Single-argument function called on map keys; return value will
        replace the property names in the output. Must return a
        string. Default calls clojure.core/name on symbols and
        keywords and clojure.core/str on everything else.

    :value-fn function

        Function to transform values in maps before writing. For each
        key-value pair in an input map, called with two arguments: the
        key (BEFORE transformation by key-fn) and the value. The
        return value of value-fn will replace the value in the output.
        If the return value is a number, boolean, string, or nil it
        will be included literally in the output. If the return value
        is a non-map collection, it will be processed recursively. If
        the return value is a map, it will be processed recursively,
        calling value-fn again on its key-value pairs. If value-fn
        returns itself, the key-value pair will be omitted from the
        output. This option does not apply to non-map collections."
  [x ^Writer writer & options]
  (let [{:keys [escape-unicode escape-js-separators escape-slash key-fn value-fn]
         :or {escape-unicode true
              escape-js-separators true
              escape-slash true
              key-fn default-write-key-fn
              value-fn default-value-fn}} options]
    (binding [*escape-unicode* escape-unicode
              *escape-js-separators* escape-js-separators
              *escape-slash* escape-slash
              *key-fn* key-fn
              *value-fn* value-fn]
      (-write x (PrintWriter. writer)))))

(defn write-str
  "Converts x to a JSON-formatted string. Options are the same as
  write."
  [x & options]
  (let [sw (StringWriter.)]
    (t/tc-ignore (apply write x sw options))
    (t/cast String (.toString sw))))

;;; JSON PRETTY-PRINTER

;; Based on code by Tom Faulhaber

(defn- pprint-array [s] 
  ((pprint/formatter-out "~<[~;~@{~w~^, ~:_~}~;]~:>") s))

(defn- pprint-object [m]
  ((pprint/formatter-out "~<{~;~@{~<~w:~_~w~:>~^, ~_~}~;}~:>") 
   (for ^{::t/ann '[t/Str t/Any]} [^{::t/ann '[t/Str t/Any]} [k v] m] [(*key-fn* k) v])))

(defn- pprint-generic [x]
  (if (some-> (t/ann-form (class x) (t/U nil Class)) .isArray)
    (do
      (assert (seqable? x))
      (pprint-array (seq x)))
    ;; pprint proxies Writer, so we can't just wrap it
    (print (with-out-str (-write x (PrintWriter. *out*))))))

(defn- pprint-dispatch [x]
  (cond (nil? x) (print "null")
        (instance? java.util.Map x) (pprint-object x)
        (instance? java.util.Collection x) (pprint-array x)
        (instance? clojure.lang.ISeq x) (pprint-array x)
        :else (pprint-generic x)))

(defn pprint
  "Pretty-prints JSON representation of x to *out*. Options are the
  same as for write except :value-fn, which is not supported."
  [x & options]
  (let [{:keys [escape-unicode escape-slash key-fn]
         :or {escape-unicode true
              escape-slash true
              key-fn default-write-key-fn}} options]
    (binding [*escape-unicode* escape-unicode
              *escape-slash* escape-slash
              *key-fn* key-fn]
      (t/tc-ignore
        (pprint/with-pprint-dispatch pprint-dispatch
          (pprint/pprint x))))))

(load "json_compat_0_1")

;; Local Variables:
;; mode: clojure
;; eval: (define-clojure-indent (codepoint-case (quote defun)))
;; End:
